execute pathogen#infect()
syntax on
filetype plugin indent on

"How many columns does a tab count for?
set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4
set number
set mouse=a

set background=dark
colorscheme solarized

let g:pep8_map='<leader>8'
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

map <leader>n :NERDTreeToggle<CR>
