set nocompatible
execute pathogen#infect()

syntax on
filetype plugin indent on

set colorcolumn=80

set tabstop=4       "A tab is four spaces
set expandtab
set softtabstop=4
set shiftwidth=4   " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
                  set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set backspace=indent,eol,start
                    " allow backspacing over everything in insert mode
set autoindent      " always set autoindenting on
set copyindent      " copy the previous indentation on autoindenting

set number          "Show line numbers
set scrolloff=3     "More context around cursor

set virtualedit=onemore    " allow cursor one line beyond last line
set ttyfast            " smoother changes

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.pyc
set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep

set nobackup

set title     " show title of the file in vim title bar
set ls=2      " show status bar with file path and name
set showmode  " show the current mode of the editor

"""
"""AESTHETICS
"""
set background=dark
colorscheme solarized

"""
"""KEYBOARD
"""
"""let mapleader = "," "Avoid pinky stretch

let g:pep8_map='<leader>8'
au FileType python set omnifunc=pythoncomplete#Complete

let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

map <leader>n :NERDTreeToggle<CR>

set mouse=a         "Enable mouse
