# ~/.zshenv is sourced before ~/.zshrc, and is sourced regardless
# of whether or not the shell is interactive.

export OS=$(uname)

# Kick-ass developers enable warnings and explicitely ignore annoying ones
export PYTHONWARNINGS="d, ignore:::imp, ignore:unclosed, ignore::DeprecationWarning, ignore::PendingDeprecationWarning,
ignore::ImportWarning"
