# ~/.zshenv is sourced before ~/.zshrc, and is sourced regardless
# of whether or not the shell is interactive.

export OS=$(uname)

# Enable all warnings except Deprecation warnings
export PYTHONWARNINGS="d, ignore:::imp, ignore:unclosed, ignore::DeprecationWarning, ignore::PendingDeprecationWarning,
ignore::ImportWarning"

#################
# POPULATE $PATH
#################
# if tmux is running, the path was already populated
# lets avoid duplicate entries, it causes havoc when changing python envs
colonise() {
    cat $1 | tr "\n" ":"
}
# We store %PATH entries in ~/.zsh_path and ~/.zsh_path_local
for file in ~/.zsh_{path,path_local}; do
    [ -r "$file" ] && export PATH=`colonise $file`:$PATH
done
unset file
