# load zgen
source "${HOME}/.zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # Plugins
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/tmux

    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-completions
    zgen load zsh-users/zsh-history-substring-search

    # Note that the agnoster theme requires a powerline font!
    zgen oh-my-zsh themes/agnoster

    # save all to init script
    zgen save
fi
